### ISSUE TITLE
Setlist: rename "block break" to "announcement"

### ISSUE THREAD

**Issue by computi71** [computi71/bandregie#248]
The separator introduced in #241 was called a *block break* (`Blockgrenze`). That name describes the line, not what happens at it: the band does not play, it talks — band intro, retuning, a word about the next song. "Announcement" (German *Sprechpause*) is what the band calls it on paper, so that is what the app should call it.

Scope:
- German strings and the help page in `app/bootstrap.php`
- Translations in their original seeds (29, 114, 118), each with a guarded `DELETE` so an existing installation gets the new wording — the earliest seed wins, so the guard has to sit in the file that re-inserts the value
- Drop the keys nobody displays any more: `sl_block`, `sl_block_hint`, `sl_block_note_edit` (seed 115 disappears with them)
- Code comments that describe the concept

Not in scope: the identifiers stay as they are (`sl_block_*`, `is_break = 3`, `.block-line`). Renaming them would mean moving translations for no gain in readability.
